// Tipos que los *.meta.json no pueden expresar (dueño: bruno). scripts/build-types.mjs los usa en lugar de lo que deduce
// del meta.json. Claves `Componente.miembro`; valores, tipos de TypeScript que pueden nombrar lo exportado por
// types/shared.d.ts. Si el generador no sabe leer un tipo del meta.json y no hay entrada aquí, el build se detiene: así
// ningún evento ni prop nuevo queda como `any` sin que nadie lo decida.

/** Props: tipo completo (sin `| undefined`; la opcionalidad sale del meta.json). */
export const props = {
  'GAvatar.color': "'neutral' | GranaCategory | `${GranaCategory}` | null",
  'GAvatar.categories': '0 | GranaCategory',
  'GBreadcrumbs.items': 'BreadcrumbItem[]',
  'GCalendar.events': 'CalendarEvent[]',
  'GCalendar.resources': 'Array<{ id: GranaKey; label?: string; [key: string]: unknown }> | null',
  'GCalendar.availability': 'Array<Record<string, unknown>>',
  'GCalendar.blocks': 'Array<Record<string, unknown>>',
  'GCard.meta': 'CardMeta[]',
  'GCard.menu': 'MenuItem[]',
  'GCard.skeleton': 'Record<string, boolean | number> | null',
  'GCard.modelValue': 'boolean | unknown[] | string | number',
  'GCheckbox.modelValue': 'boolean | unknown[]',
  'GCheckboxGroup.modelValue': 'Array<string | number | boolean>',
  'GCombobox.modelValue': 'string | number | null | Array<string | number>',
  'GCombobox.custom': 'string | string[]',
  'GCombobox.options': 'Array<ComboboxOption | ComboboxOptionGroup>',
  'GCombobox.selectedOption': 'ComboboxOption | null',
  'GCombobox.filter': 'boolean | ((option: ComboboxOption, query: string) => boolean)',
  'GCombobox.selectedOptions': 'ComboboxOption[]',
  'GDatePicker.modelValue': 'string | DateRange | null',
  'GDatePicker.disabledDates': '((date: Date) => boolean) | null',
  'GDatePicker.proximity': 'unknown[]',
  'GErrorSummary.errors': 'FormError[] | null',
  'GErrorSummary.labels': '{ title?: string | ((count: number) => string) }',
  'GFileField.modelValue': 'FileEntry[] | null',
  'GFileField.uploader': 'FileUploader | null',
  'GFilterBar.fields': 'FilterField[]',
  'GFilterBar.filters': 'Filter[]',
  'GForm.errors': 'Record<string, string | null | undefined>',
  'GForm.warnings': 'Record<string, string | null | undefined>',
  'GInputGroupSelect.options': 'Array<SelectOption | SelectOptionGroup>',
  'GMenu.items': 'MenuItem[]',
  'GRadioGroup.options': 'RadioOption[]',
  'GSelect.options': 'Array<SelectOption | SelectOptionGroup>',
  'GSidebar.items': 'SidebarItem[]',
  'GSpeechHost.speech': 'Speech | null',
  'GSpeechPill.speech': 'Speech | null',
  'GSpeechTrigger.speech': 'Speech | null',
  'GStatus.action': "StatusConditionOptions['action']",
  'GStatus.link': "StatusConditionOptions['link']",
  'GStatus.origin': "StatusConditionOptions['origin']",
  'GStatus.status': 'Status',
  'GStatusIsland.status': 'Status',
  'GStatusMark.status': 'Status',
  'GStepper.steps': 'StepperStep[]',
  'GSummary.avatar': 'boolean | AvatarSpec',
  'GSummary.facts': 'SummaryFact[]',
  'GSummary.status': '{ label: string; color?: GranaColor } | null',
  'GSummary.diff': 'SummaryDiff | null',
  'GTable.columns': 'TableColumn[]',
  'GTable.rows': 'Array<Record<string, any>>',
  'GTable.sort': 'TableSort | null',
  'GTable.selected': 'GranaKey[]',
  'GTable.filters': 'Filter[]',
  'GTabs.items': 'TabItem[]',
  'GToaster.toaster': 'Toaster | null',
  'GTranscript.transcript': 'Transcript | null',
  'GTranscript.selected': 'string[]',
  'GTranscript.targets': 'SpeechTarget[] | null',
  'GTranscript.roles': 'SpeechRole[] | null',
  'GTranscript.speakerColors': 'number | null',
  'GWidget.actions': 'MenuItem[]'
}

/** Eventos: tipo del argumento (`void` = sin argumento). */
export const events = {
  'GAvatarMotion.done': "'success' | 'warning' | 'error'",
  'GBreadcrumbs.navigate': 'BreadcrumbsNavigateEvent',
  'GCalendar.range-change': '{ start: Date; end: Date; view: string; timezone: string }',
  'GCard.update:modelValue': 'boolean | unknown[] | string | number',
  'GCard.action': '{ id: GranaKey; checked?: boolean }',
  'GCombobox.update:modelValue': 'string | number | null | Array<string | number>',
  'GCombobox.update:custom': 'string | string[]',
  'GCombobox.change': 'ComboboxChange | ComboboxMultipleChange',
  'GCombobox.search': 'string',
  'GCombobox.more': 'string',
  'GCombobox.create': 'string',
  'GDatePicker.update:modelValue': 'string | DateRange | null',
  'GDatePicker.change': 'string | DateRange | null',
  'GDialog.dismiss': "{ reason: 'escape' | 'backdrop' | 'close'; preventDefault(): void }",
  'GFileField.update:modelValue': 'FileEntry[]',
  'GFileField.change': 'FileFieldChange',
  'GFileField.reject': 'FileFieldReject',
  'GFilterBar.update:filters': 'Filter[]',
  'GForm.submit': 'FormSubmitEvent',
  'GForm.invalid': 'FormInvalidEvent',
  'GHelper.toggle': "{ open: boolean; presentation: 'popover' | 'sheet' }",
  'GMenu.select': 'MenuSelectEvent',
  'GPagination.update:page': 'number',
  'GRadioGroup.update:modelValue': 'string | number | boolean',
  'GSidebar.update:modelValue': 'GranaKey',
  'GStatus.remove': 'StatusRemoveReason',
  'GStepper.update:modelValue': 'GranaKey',
  'GTable.update:sort': 'TableSort',
  'GTable.update:selected': 'GranaKey[]',
  'GTable.update:filters': 'Filter[]',
  'GTable.update:page': 'number',
  'GTabs.update:modelValue': 'GranaKey',
  'GTabs.change': "{ id: GranaKey; index: number; source: 'keyboard' | 'pointer' | 'menu'; preventDefault(): void }",
  'GTranscript.update:selected': 'string[]',
  'GTranscript.change': '{ kind: string; ids: string[] }',
  'GTranscript.insert': 'TranscriptDerived',
  'GTranscript.undo-insert': 'TranscriptDerived',
  'GWidgetConfig.update:tab': 'GranaKey',
  'GWidgetGrid.update:modelValue': 'Array<Record<string, any>>',
  'GWidgetGrid.change': "{ layout: Array<Record<string, any>>; reason: 'move' | 'resize'; id: GranaKey }"
}

/** Slots: tipo del alcance. */
export const slots = {
  'GBreadcrumbs.link': "{ item: BreadcrumbItem | BreadcrumbChild; index: number; current: boolean; from: BreadcrumbsNavigateEvent['from']; attrs: Record<string, any>; content: () => GranaSlotContent }",
  'GBreadcrumbs.icon': '{ item: BreadcrumbItem; index: number }',
  'GCombobox.option': '{ option: ComboboxOption; active: boolean; selected: boolean; query: string }',
  'GCombobox.lead': '{ option: ComboboxOption }',
  'GCombobox.value': '{ option: ComboboxOption | null; custom: string }',
  'GCombobox.preview': '{ option: ComboboxOption }',
  'GCombobox.empty': '{ query: string }',
  'GCombobox.load-error': '{ message: string; query: string }',
  'GCombobox.chosen': '{ option: ComboboxOption | null; custom: string }',
  'GDialog.default': '{ close: () => void }',
  'GDialog.footer': '{ close: () => void }',
  'GDialog.header': '{ titleId: string; descriptionId: string }',
  'GMenu.item': '{ item: MenuItem; active: boolean; checked: boolean }',
  'GMenu.icon': '{ item: MenuItem }',
  'GRadioGroup.option': '{ option: RadioOption; index: number; checked: boolean; disabled: boolean }',
  'GRadioGroup.icon': '{ option: RadioOption; index: number; checked: boolean }',
  'GSelect.option': '{ option: SelectOption; selected: boolean; active: boolean }',
  'GSelect.value': '{ option: SelectOption | null }',
  'GSelect.icon': '{ option: SelectOption }',
  'GSidebar.item': '{ item: SidebarItem; active: boolean; collapsed: boolean; level: number }',
  'GSidebar.icon': '{ item: SidebarItem }',
  'GStepper.content': '{ step: StepperStep; index: number; state: string }',
  'GStepper.icon': '{ step: StepperStep; index: number; state: string }',
  'GStepper.label': '{ step: StepperStep; index: number; state: string }',
  'GStepper.description': '{ step: StepperStep; index: number; state: string }',
  'GTable.cell-{key}': '{ row: Record<string, any>; value: any; column: TableColumn }',
  'GTable.leading-{key}': '{ row: Record<string, any> }',
  'GTable.row-actions': '{ row: Record<string, any> }',
  'GTable.empty': '{ filtered: boolean; clear: () => void }',
  'GTabs.panel-{id}': '{ item: TabItem; active: boolean }',
  'GTabs.panel': '{ item: TabItem; active: boolean }',
  'GTabs.icon': '{ item: TabItem; index: number; active: boolean }',
  'GTabs.label': '{ item: TabItem; index: number; active: boolean }'
}

/** Lo que el componente expone por `ref` (defineExpose / expose). Los `methods` del meta.json deben estar aquí. */
export const exposed = {
  GAdaptiveLayout: '{ refresh(): void }',
  GCard: "{ readonly size: string; readonly layout: string }",
  GDatePicker: '{ open(): void; close(): void; focus(): void }',
  GFileField: '{ add(files: FileList | File[]): FileFieldAddResult; open(): void; focus(): void }',
  GForm: '{ showErrors(): Promise<FormError[]>; focusFirstError(): Promise<boolean>; resetState(): void }',
  GSidebar: '{ open(): void; close(): void; toggle(): void; focus(): void }',
  GTranscript: '{ focus(): void; undo(): void; redo(): void }',
  GWidget: '{ focusMenu(): void; readonly level: string; readonly shape: string }',
  GWidgetConfig: '{ announce(text: string): void }',
  GWidgetGallery: '{ announce(text: string): void }',
  GWidgetGrid: "{ focusMenu(id: GranaKey): void; focusHandle(id: GranaKey, what?: string): void }"
}

/** Componentes cuyo `methods` del meta.json describe un gestor, no lo expuesto por `ref`. */
export const managerMethods = ['GSpeechHost', 'GStatusIsland', 'GToaster']

/** Alias de registro: Vue resuelve <g-datepicker> como GDatepicker (index.js `install`). */
export const aliases = { GDatepicker: 'GDatePicker' }
