// GCombobox sobre el COMPONENTE REAL del playground (packages/vue/playground, #sec-combobox; entrada @grana/vue/combobox),
// en Chromium, Firefox y WebKit. Port de design/lab/combobox/r01/verificar.mjs (kiwi, 105 comprobaciones por motor) y de
// los puntos de navegador del contrato (design/contracts/combobox.md «Verificación · Playwright»; DECISIONS.md #329 a
// #338): semántica APG, foco por Tab sin abrir, antirrebote, pendiente, reglas de seguridad de Tab e Intro (#333), estados
// de la lista, Δ0, capa superior, activa siempre a la vista sin mover la página, grupos, texto libre, agregar, FormData,
// GFormRow de tres, dentro de GDialog, 500 opciones < 150 ms (mediana, con un worker), móvil 375 y 320, RTL, contraste y consola limpia.
// Lo propio de la forma (A, B, C) está en combobox-forma.spec.mjs; el movimiento, en personalidad-combobox.spec.mjs.
import { test, expect } from '@playwright/test'
import { calls, contrast, frames, geo, live, open, out, st, type, watchConsole } from './combobox-helpers.mjs'

test.describe('GCombobox · componente real (combobox.md)', () => {
  test('reposo: semántica del patrón, tres hijos en flujo, enfocar por Tab no abre', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    const rest = await page.evaluate(() => {
      const i = document.getElementById('cb-pac')
      const root = i.closest('.g-combobox')
      const list = document.getElementById(i.getAttribute('aria-controls'))
      const flow = [...root.children].filter((c) => !['absolute', 'fixed'].includes(getComputedStyle(c).position) && getComputedStyle(c).display !== 'none')
      return {
        tag: i.tagName, type: i.type, role: i.getAttribute('role'), exp: i.getAttribute('aria-expanded'), auto: i.getAttribute('aria-autocomplete'), pop: i.getAttribute('aria-haspopup'),
        ac: i.getAttribute('autocomplete'), cap: i.getAttribute('autocapitalize'), spell: i.getAttribute('spellcheck'), name: i.getAttribute('name'), act: i.getAttribute('aria-activedescendant'),
        label: document.querySelector('label[for="cb-pac"]')?.textContent.trim(), listRole: list?.getAttribute('role'), listBy: document.getElementById(list?.getAttribute('aria-labelledby'))?.textContent.trim(),
        flow: flow.map((c) => c.className.split(' ')[0]), kids: [...root.children].map((c) => c.className.split(' ')[0]),
        liveAttrs: ['role', 'aria-live', 'aria-atomic'].map((a) => document.getElementById('cb-pac-live').getAttribute(a)).join(),
        rootIsInput: root.classList.contains('g-input'), popover: document.getElementById('cb-pac-popup').getAttribute('popover')
      }
    })
    expect(rest).toMatchObject({ tag: 'INPUT', type: 'text', role: 'combobox', exp: 'false', auto: 'list', pop: 'listbox', ac: 'off', cap: 'none', spell: 'false', name: null, act: null, label: 'Paciente', listRole: 'listbox', listBy: 'Paciente', rootIsInput: true, popover: 'manual' })
    expect(rest.flow).toEqual(['g-input__label', 'g-input__row', 'g-input__support'])
    expect(rest.kids.slice(3)).toEqual(['g-combobox__live', 'g-combobox__popup'])
    expect(rest.liveAttrs).toBe('status,polite,true')
    await page.focus('#cb-pac')
    await frames(page)
    const s = await st(page, 'cb-pac')
    expect(s.open).toBe(false)
    expect(s.expanded).toBe('false')
    expect(s.popOpen).toBe(false)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('escribir: pista de mínimo, antirrebote (una búsqueda por pausa), resultados, primera activa, <mark>, un anuncio, Δ0 y capa superior', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page, { fast: false })
    await page.focus('#cb-pac')
    await frames(page, 3) // WebKit termina de llevar el campo enfocado a la vista
    const g0 = await geo(page, 'cb-pac')
    const c0 = await calls(page)
    await page.keyboard.type('m')
    await page.waitForTimeout(350)
    let s = await st(page, 'cb-pac')
    expect(s.open).toBe(true)
    expect(s.n).toBe(0)
    expect(s.status).toMatch(/al menos 2 caracteres/)
    expect(s.statusKind).toContain('g-combobox__status--hint')
    expect(await calls(page), 'por debajo de minChars no se emite search').toBe(c0)
    await page.keyboard.type('ar', { delay: 40 })
    await page.waitForTimeout(900)
    s = await st(page, 'cb-pac')
    expect(await calls(page), 'antirrebote: una búsqueda por pausa, no una por tecla').toBe(c0 + 1)
    expect(s.expanded).toBe('true')
    expect(s.n).toBe(20)
    expect(s.acts).toEqual(['more'])
    expect(s.active).toBe(s.first)
    expect(s.activeOk).toBe(true)
    expect(s.oneActive).toBe(true)
    expect(s.focus, 'el foco real no sale del campo').toBe('cb-pac')
    expect(await page.evaluate(() => document.querySelector('#cb-pac-list [role=option] mark.g-summary__mark')?.textContent.toLowerCase())).toBe('mar')
    expect(await page.locator('#cb-pac-list .g-combobox__action--more').textContent()).toMatch(/^Mostrar más \(20 de \d+\)$/)
    await page.waitForTimeout(800)
    const lv = (await live(page)).filter((x) => /resultados/.test(x.text))
    expect(lv.length, JSON.stringify(lv)).toBe(1)
    expect(lv[0].text).toMatch(/^20 de \d+ resultados$/)
    expect(lv[0].dialog).toBe(false)
    const g1 = await geo(page, 'cb-pac')
    expect(Math.abs(g1.top - g0.top), 'Δ0 del campo').toBeLessThan(0.5)
    expect(g1.sy, 'Δ0 de la página').toBe(g0.sy)
    expect(g1.sh, 'Δ0 del alto del documento').toBe(g0.sh)
    expect(g1.sw).toBeLessThanOrEqual(g1.cw)
    expect(s.popOpen, 'popover abierto: capa superior').toBe(true)
    const hit = await page.evaluate(() => {
      const r = document.querySelector('#cb-pac-list [role=option]').getBoundingClientRect()
      return Boolean(document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2)?.closest('#cb-pac-list [role=option]'))
    })
    expect(hit, 'la fila recibe el puntero').toBe(true)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('teclado: ↓ ↑ sin ciclar, Av Pág, activa siempre a la vista sin mover la página, «Mostrar más», Intro elige', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await type(page, 'cb-pac', 'mar')
    let s = await st(page, 'cb-pac')
    const ids = s.ids
    const sy = await page.evaluate(() => scrollY)
    await page.keyboard.press('ArrowDown')
    expect((await st(page, 'cb-pac')).active).toBe(ids[1])
    await page.keyboard.press('ArrowUp')
    await page.keyboard.press('ArrowUp')
    expect((await st(page, 'cb-pac')).active, 'no cicla en la primera').toBe(ids[0])
    await page.keyboard.press('PageDown')
    expect((await st(page, 'cb-pac')).active).toBe(ids[10])
    const visible = () => page.evaluate(() => {
      const a = document.querySelector('#cb-pac-list .is-active').getBoundingClientRect()
      const p = document.getElementById('cb-pac-popup').getBoundingClientRect()
      return a.top >= p.top - 1 && a.bottom <= p.bottom + 1 && a.bottom <= innerHeight
    })
    await frames(page)
    expect(await visible(), 'la activa está a la vista').toBe(true)
    await page.keyboard.press('PageDown')
    await page.keyboard.press('PageDown')
    await frames(page)
    s = await st(page, 'cb-pac')
    expect(s.activeAct, 'las filas de acción cuentan y no cicla al final').toBe('more')
    expect(await visible()).toBe(true)
    expect(await page.evaluate(() => scrollY), 'la página no se mueve').toBe(sy)
    await page.keyboard.press('Enter')
    await page.waitForTimeout(300)
    s = await st(page, 'cb-pac')
    expect(s.n).toBe(40)
    expect(s.expanded).toBe('true')
    expect(s.active, 'la activa es la primera nueva').toBe(s.ids[20])
    await page.waitForTimeout(800)
    expect((await live(page)).map((x) => x.text).filter((t) => /^40 de/.test(t)).length, 'recuento nuevo tras «Mostrar más»').toBe(1)
    const picked = s.activeText
    await page.keyboard.press('Enter')
    await frames(page)
    s = await st(page, 'cb-pac')
    expect(s.expanded).toBe('false')
    expect(s.popOpen).toBe(false)
    expect(s.token).toBe(true)
    expect(picked).toContain(s.value)
    expect(await out(page, 'cb-out-pac')).toMatch(/^paciente: p\d{6} /)
    expect(await out(page, 'cb-log')).toMatch(/^change: pac \{"value":"p\d{6}","custom":"","option":"/)
    expect(s.focus).toBe('cb-pac')
    expect(await page.evaluate(() => { const i = document.getElementById('cb-pac'); return i.selectionStart === 0 && i.selectionEnd === i.value.length }), 'tras elegir, el texto queda seleccionado').toBe(true)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('reglas de seguridad: Tab no elige la resaltada sola; Esc en dos niveles; vaciar y salir borra; limpiar', async ({ page, browserName }) => {
    const errs = await watchConsole(page)
    await open(page)
    await type(page, 'cb-pac', 'maría garcía')
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await frames(page)
    const chosen = await out(page, 'cb-out-pac')
    const label = (await st(page, 'cb-pac')).value
    expect(label).toBe('María García López')
    // Escribir sobre un valor reabre; la primera queda activa sola y Tab NO la elige
    await page.keyboard.type('jos', { delay: 15 })
    await page.waitForTimeout(260)
    let s = await st(page, 'cb-pac')
    expect(s.expanded).toBe('true')
    expect(s.active).toBe(s.first)
    await page.keyboard.press('Tab')
    await frames(page)
    s = await st(page, 'cb-pac')
    expect(await out(page, 'cb-out-pac'), 'Tab no elige: el modelo no cambia').toBe(chosen)
    expect(s.value, 'el texto sin coincidencia se descarta').toBe(label)
    expect(s.expanded).toBe('false')
    expect(s.focus).not.toBe('cb-pac')
    // Esc: abierta cierra y conserva el texto; cerrada restaura y selecciona
    await page.focus('#cb-pac')
    await page.keyboard.type('zz')
    await page.waitForTimeout(200)
    await page.keyboard.press('Escape')
    s = await st(page, 'cb-pac')
    expect(s.expanded).toBe('false')
    expect(s.value).toBe('zz')
    await page.keyboard.press('Escape')
    await frames(page)
    s = await st(page, 'cb-pac')
    expect(s.value).toBe(label)
    expect(s.token).toBe(true)
    // Limpiar: botón aparte en el orden de Tab con nombre «Limpiar Paciente»
    const clr = await page.evaluate(() => {
      const b = document.getElementById('cb-pac-clear')
      const r = b.getBoundingClientRect()
      return { name: b.getAttribute('aria-labelledby').split(' ').map((id) => document.getElementById(id).textContent.trim()).join(' '), tag: b.tagName, type: b.type, w: r.width, h: r.height, tab: b.tabIndex }
    })
    expect(clr).toMatchObject({ name: 'Limpiar Paciente', tag: 'BUTTON', type: 'button', tab: 0 })
    expect(Math.min(clr.w, clr.h)).toBeGreaterThanOrEqual(24)
    // WebKit no enfoca botones con Tab salvo ajuste del sistema: allí se enfoca directamente
    if (browserName === 'webkit') await page.focus('#cb-pac-clear')
    else await page.keyboard.press('Tab')
    expect(await page.evaluate(() => document.activeElement.id)).toBe('cb-pac-clear')
    await page.keyboard.press('Enter')
    await frames(page)
    s = await st(page, 'cb-pac')
    expect(await out(page, 'cb-out-pac')).toMatch(/^paciente: null/)
    expect(s.value).toBe('')
    expect(s.focus, 'limpiar devuelve el foco al campo').toBe('cb-pac')
    expect(await page.locator('#cb-pac-clear').count()).toBe(0)
    // Vaciar y salir borra
    await type(page, 'cb-dx', 'cefa')
    await page.keyboard.press('Enter')
    await frames(page)
    expect(await out(page, 'cb-out-dx')).toBe('dx: R51')
    await page.keyboard.press('Backspace')
    await page.keyboard.press('Tab')
    await frames(page)
    expect(await out(page, 'cb-out-dx')).toBe('dx: null')
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('estados de la lista: sin resultados y error de carga con «Reintentar», ambos anunciados', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await type(page, 'cb-err', 'zzzz', { wait: 400 })
    let s = await st(page, 'cb-err')
    expect(s.n).toBe(0)
    expect(s.listHidden).toBe(true)
    expect(s.statusKind).toContain('g-combobox__status--empty')
    expect(s.status).toBe('Sin resultados para «zzzz»')
    await page.waitForTimeout(800)
    expect((await live(page)).some((x) => x.text === 'Sin resultados para «zzzz»')).toBe(true)
    await page.keyboard.press('Escape')
    await page.keyboard.press('Escape')
    // Error de carga: en el panel, no en el campo; la fila «Reintentar» sustituye a «Mostrar más»
    await page.click('#cb-fail')
    await type(page, 'cb-err', 'm', { wait: 400 }) // una sola tecla: una sola búsqueda, la que falla
    s = await st(page, 'cb-err')
    expect(s.statusKind).toContain('g-combobox__status--error')
    expect(s.status).toBe('No se pudieron cargar los resultados.')
    expect(s.acts).toEqual(['retry'])
    expect(await page.evaluate(() => { const i = document.getElementById('cb-err'); return [i.getAttribute('aria-invalid'), i.closest('.g-combobox').classList.contains('is-invalid'), Boolean(document.getElementById('cb-err-status').closest('[role=listbox]'))] })).toEqual([null, false, false])
    await page.waitForTimeout(800)
    expect((await live(page)).some((x) => x.text === 'No se pudieron cargar los resultados.'), 'el error de carga se anuncia').toBe(true)
    await page.keyboard.press('ArrowDown')
    expect((await st(page, 'cb-err')).activeAct).toBe('retry')
    await page.keyboard.press('Enter')
    await page.waitForTimeout(400)
    s = await st(page, 'cb-err')
    expect(s.n, 'Intro reintenta: llegan resultados').toBe(20)
    expect(s.status).toBe('')
    expect(s.expanded).toBe('true')
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('tiempos reales: cargando no vacía la lista (aria-busy) e Intro no elige un resultado obsoleto', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page, { fast: false })
    await type(page, 'cb-pac', 'mar', { wait: 1100 })
    let s = await st(page, 'cb-pac')
    expect(s.n).toBe(20)
    const firstMar = s.activeText
    await page.keyboard.type('t')
    await page.keyboard.press('Enter') // en el antirrebote: la resaltada sola de «mar» no se elige
    await page.waitForTimeout(330) // antirrebote cumplido, la red aún no responde
    s = await st(page, 'cb-pac')
    expect(s.n, 'siguen los resultados anteriores').toBe(20)
    expect(s.busy).toBe('true')
    expect(s.status).toBe('')
    expect(await page.evaluate(() => document.getElementById('cb-pac').getAttribute('aria-busy')), 'indicador de GInput').toBe('true')
    await page.keyboard.press('Enter') // cargando: tampoco
    expect(await out(page, 'cb-out-pac')).toMatch(/^paciente: null/)
    expect((await st(page, 'cb-pac')).expanded).toBe('true')
    await page.waitForTimeout(700)
    s = await st(page, 'cb-pac')
    expect(s.busy).toBe(null)
    expect(s.active).toBe(s.first)
    expect(s.activeText).not.toBe(firstMar)
    expect(s.activeText, 'la primera de «mart»').toContain('Martínez')
    await page.keyboard.press('Enter')
    await frames(page)
    expect(await out(page, 'cb-out-pac')).toMatch(/^paciente: p\d{6}/)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('diagnóstico (filtro local): grupos, código, sin acentos, lista completa con ↓ y aria-selected único', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await type(page, 'cb-dx', 'diab')
    let s = await st(page, 'cb-dx')
    expect(s.n).toBe(2)
    const grp = await page.evaluate(() => [...document.querySelectorAll('#cb-dx-list [role=group]')].map((g) => [g.parentElement.getAttribute('role'), document.getElementById(g.getAttribute('aria-labelledby'))?.textContent]))
    expect(grp).toEqual([['presentation', 'Endocrinas, nutricionales y metabólicas (E00–E89)']])
    expect(s.activeText).toContain('E10.9')
    expect(await page.evaluate(() => document.getElementById('cb-dx').getAttribute('aria-required') + '|' + document.getElementById('cb-dx').required)).toBe('true|false')
    await page.keyboard.press('Escape')
    await page.keyboard.press('Escape')
    await type(page, 'cb-dx', 'j45')
    expect((await st(page, 'cb-dx')).activeText).toContain('Asma')
    await page.keyboard.press('Escape')
    await page.keyboard.press('Escape')
    await type(page, 'cb-dx', 'migrana')
    s = await st(page, 'cb-dx')
    expect(s.n).toBe(1)
    expect(s.activeText).toContain('Migraña')
    await page.keyboard.press('Enter')
    await frames(page)
    expect(await out(page, 'cb-out-dx')).toBe('dx: G43.9')
    await page.keyboard.press('ArrowDown')
    await frames(page)
    s = await st(page, 'cb-dx')
    expect(s.n, '↓ abre la lista completa').toBe(34)
    expect(s.activeText, '↓ activa la elegida').toContain('Migraña')
    const sel = await page.evaluate(() => [...document.querySelectorAll('#cb-dx-list [aria-selected=true]')].map((o) => [o.textContent.includes('G43.9'), Boolean(o.querySelector('.g-combobox__check'))]))
    expect(sel).toEqual([[true, true]])
    expect(await page.evaluate(() => document.querySelectorAll('#cb-dx-list [role=option][tabindex]').length)).toBe(0)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('texto libre (v-model:custom) y fila «Agregar» (create con el foco ya en el campo)', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await type(page, 'cb-med', 'paracetamol jarabe')
    let s = await st(page, 'cb-med')
    expect(s.acts).toEqual(['custom'])
    expect(s.status).toMatch(/Sin resultados/)
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await frames(page)
    expect(await out(page, 'cb-out-med')).toBe('med: null · libre: "paracetamol jarabe"')
    s = await st(page, 'cb-med')
    expect(s.custom && s.token).toBe(true)
    expect(s.about).toBe('Texto libre')
    expect(s.describedby.split(' ')[0]).toBe('cb-med-about')
    // Con coincidencias la fila sigue; con una etiqueta idéntica a la vista, no
    await page.keyboard.type('ibu', { delay: 15 })
    await page.waitForTimeout(200)
    s = await st(page, 'cb-med')
    expect(s.n).toBe(1)
    expect(s.acts).toEqual(['custom'])
    await page.keyboard.press('Enter') // elige la opción: custom se vacía
    await frames(page)
    expect(await out(page, 'cb-out-med')).toBe('med: m2 · libre: ""')
    // Al salir, allowCustom conserva el texto
    await page.keyboard.type('Otro fármaco', { delay: 10 })
    await page.keyboard.press('Tab')
    await frames(page)
    expect(await out(page, 'cb-out-med')).toBe('med: null · libre: "Otro fármaco"')
    // Agregar: la última fila; no cambia el valor por sí misma (la aplicación agrega y selecciona)
    await type(page, 'cb-cli', 'Nuevo SA')
    s = await st(page, 'cb-cli')
    expect(s.acts).toEqual(['create'])
    expect(s.ids[s.ids.length - 1]).toBe('cb-cli-opt-create')
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await frames(page)
    s = await st(page, 'cb-cli')
    expect(await out(page, 'cb-out-cli')).toBe('cliente: c6 · creado: Nuevo SA')
    expect(s.value).toBe('Nuevo SA')
    expect(s.focus).toBe('cb-cli')
    expect(s.expanded).toBe('false')
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('GFormRow de tres (Δ top ≤ 1px, sin huecos), selectedOption, estados y FormData', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await page.locator('#cb-row').scrollIntoViewIfNeeded()
    const row = await page.evaluate(() => {
      const r = document.getElementById('cb-row')
      const rr = r.getBoundingClientRect()
      const boxes = ['cb-f-pac', 'cb-f-sel', 'cb-f-nota'].map((id) => document.getElementById(id).closest('.g-input__control, .g-select__control').getBoundingClientRect())
      const kids = [...r.children].map((c) => c.getBoundingClientRect())
      return { lines: r.dataset.lines, tops: boxes.map((b) => b.top), hs: boxes.map((b) => b.height), start: kids[0].left - rr.left, end: rr.right - kids[kids.length - 1].right, kids: r.children.length }
    })
    expect(row.lines).toBe('1')
    expect(row.kids).toBe(3)
    expect(Math.max(...row.tops) - Math.min(...row.tops), `tops ${row.tops}`).toBeLessThanOrEqual(1)
    expect(Math.max(...row.hs) - Math.min(...row.hs), `altos ${row.hs}`).toBeLessThanOrEqual(1)
    expect(Math.abs(row.start)).toBeLessThanOrEqual(1)
    expect(Math.abs(row.end), 'la fila llena el ancho').toBeLessThanOrEqual(1)
    let s = await st(page, 'cb-f-pac')
    expect(s.value, 'selectedOption pinta el valor inicial sin options').toBe('Daniela Chávez Flores')
    expect(s.token).toBe(true)
    expect(s.about).toMatch(/^Exp\. \d{6} · \d+ años$/)
    // Solo lectura, deshabilitado y error
    const ro = await page.evaluate(() => {
      const i = document.getElementById('cb-ro'); const root = i.closest('.g-combobox')
      const d = document.getElementById('cb-dis'); const b = document.getElementById('cb-bad')
      return { ro: [i.readOnly, i.getAttribute('aria-readonly'), i.value, Boolean(root.querySelector('.g-combobox__clear')), Boolean(root.querySelector('.g-combobox__arrow'))], dis: [d.disabled, Boolean(d.closest('.g-combobox').querySelector('.g-combobox__arrow'))], bad: [b.getAttribute('aria-invalid'), b.getAttribute('aria-required'), b.closest('.g-combobox').querySelector('.g-input__message').textContent.includes('Elige un diagnóstico')] }
    })
    expect(ro).toEqual({ ro: [true, 'true', 'Hipertensión esencial (primaria)', false, false], dis: [true, false], bad: ['true', 'true', true] })
    await page.click('#cb-ro')
    await page.keyboard.press('ArrowDown')
    await page.keyboard.type('x')
    s = await st(page, 'cb-ro')
    expect([s.expanded, s.popOpen, s.focus, s.value]).toEqual(['false', false, 'cb-ro', 'Hipertensión esencial (primaria)'])
    // Envío: value de la opción; el texto libre, en su clave
    await type(page, 'cb-f-med', 'Fórmula magistral')
    await page.keyboard.press('Tab')
    await type(page, 'cb-f-dx', 'i10')
    await page.keyboard.press('Enter')
    await page.click('#cb-send')
    await frames(page)
    const sent = JSON.parse((await out(page, 'cb-out-sent')).replace('FormData: ', ''))
    expect(sent).toEqual({ paciente: 'p001399', nota: '', medicamento: '', medicamento_libre: 'Fórmula magistral', dx: 'I10' })
    expect(await page.evaluate(() => [...document.querySelectorAll('#cb-form input[role=combobox]')].every((i) => !i.name)), 'los visibles no llevan name').toBe(true)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('dentro de un GDialog: abre, filtra, el puntero elige, el anuncio va dentro y Esc no cierra el diálogo', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await page.click('#cb-d-open')
    await page.waitForSelector('#cb-dlg[open]')
    await type(page, 'cb-d-dx', 'asma')
    let s = await st(page, 'cb-d-dx')
    expect(s.n).toBe(1)
    expect(s.popOpen).toBe(true)
    expect(await page.evaluate(() => Boolean(document.getElementById('cb-d-dx-popup').closest('#cb-dlg')))).toBe(true)
    await page.waitForTimeout(800)
    const lv = (await live(page)).filter((x) => x.text === '1 resultado')
    expect(lv.length).toBe(1)
    expect(lv[0].dialog, 'la región viva queda dentro del diálogo').toBe(true)
    await page.keyboard.press('Escape')
    s = await st(page, 'cb-d-dx')
    expect(s.expanded).toBe('false')
    expect(await page.evaluate(() => document.getElementById('cb-dlg').open), 'Esc cierra la lista, no el diálogo').toBe(true)
    await page.keyboard.press('Escape') // restaura el texto: tampoco llega al diálogo
    expect(await page.evaluate(() => document.getElementById('cb-dlg').open)).toBe(true)
    await page.keyboard.type('asma', { delay: 15 })
    await page.waitForTimeout(200)
    await page.click('#cb-d-dx-list [role=option]')
    await frames(page)
    expect(await out(page, 'cb-out-dx')).toBe('dx: J45.9')
    s = await st(page, 'cb-d-dx')
    expect(s.focus, 'el clic en la fila no quita el foco del campo').toBe('cb-d-dx')
    expect(await page.evaluate(() => document.getElementById('cb-dlg').open)).toBe(true)
    expect(errs, errs.join('\n')).toEqual([])
  })

  // Medida robusta a la carga sin aflojar el tope (como combobox-multiple-perf.spec.mjs, #428, y la voz F2, #264): dentro
  // de la página, de la tecla al segundo cuadro; una apertura en frío (se anota) y cinco en caliente; se exige la MEDIANA
  // de las cinco < 150 ms, y solo con un worker (con varios, o con la máquina cargada, la cifra es del equipo y se anota):
  //   GRANA_PW_PORT=4210 npx playwright test tests/combobox.spec.mjs -g quinientas --workers=1
  test('quinientas opciones: tope de 50, «Mostrar más», abrir < 150 ms y el filtro recorre todas', async ({ page, browserName }, testInfo) => {
    const errs = await watchConsole(page)
    await open(page)
    const runs = []
    for (let n = 0; n < 6; n++) {
      await page.focus('#cb-big')
      await page.waitForTimeout(150)
      runs.push(await page.evaluate(() => new Promise((resolve) => {
        const i = document.getElementById('cb-big')
        const t0 = performance.now()
        i.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }))
        requestAnimationFrame(() => requestAnimationFrame(() => resolve(performance.now() - t0)))
      })))
      const s = await st(page, 'cb-big')
      expect(s.n, `apertura ${n + 1}`).toBe(50)
      expect(s.acts).toEqual(['more'])
      if (n === 5) break
      await page.keyboard.press('Escape')
      await page.waitForTimeout(150)
      await page.keyboard.press('Escape')
    }
    let s = await st(page, 'cb-big')
    expect(s.n).toBe(50)
    expect(s.acts).toEqual(['more'])
    expect(await page.locator('#cb-big-list .g-combobox__action--more').textContent()).toBe('Mostrar más (50 de 500)')
    const ms = runs.map(Math.round)
    const warm = ms.slice(1)
    const median = [...warm].sort((a, b) => a - b)[2]
    const gate = testInfo.config.workers === 1
    // Cifra por motor (informe de bruno; con la ficha GSummary en cada fila, #356): anotada en el reporte y en la salida
    testInfo.annotations.push({ type: 'perf', description: `abrir con 500 opciones (50 fichas pintadas) en ${browserName}: frío ${ms[0]} ms; caliente ${warm.join(' / ')} ms (mediana ${median}; tope 150 ms)${gate ? ' (exigido)' : ' (registrado: varios workers)'}` })
    console.log(`[500 opciones] ${browserName}: frío ${ms[0]} ms; caliente ${warm.join(' / ')} ms (mediana ${median})`)
    if (gate) expect(median, `abrir con 500 opciones: mediana ${median} ms (${warm.join(' / ')}; frío ${ms[0]})`).toBeLessThan(150)
    await page.keyboard.type('499', { delay: 15 })
    await page.waitForTimeout(200)
    s = await st(page, 'cb-big')
    expect(s.n).toBe(1)
    expect(s.activeText).toContain('Insumo 499')
    expect(errs, errs.join('\n')).toEqual([])
  })

  for (const vw of [375, 320]) {
    test(`móvil ${vw}px: sin desborde, hoja arriba de ancho completo con su campo, opciones ≥ 44px y foco de vuelta`, async ({ page }) => {
      const errs = await watchConsole(page)
      await open(page, { width: vw, height: 720 })
      let g = await geo(page, 'cb-pac')
      expect(g.sw, 'sin desbordamiento horizontal').toBeLessThanOrEqual(g.cw)
      const trig = await page.evaluate(() => { const i = document.getElementById('cb-pac'); return [i.getAttribute('aria-haspopup'), i.getAttribute('inputmode'), i.getAttribute('aria-controls'), i.getAttribute('aria-autocomplete'), i.closest('.g-combobox').classList.contains('is-surface')] })
      expect(trig).toEqual(['dialog', 'none', 'cb-pac-surface', null, true])
      await page.click('#cb-pac')
      await page.waitForSelector('#cb-pac-surface[open]')
      await frames(page, 3)
      let s = await st(page, 'cb-pac')
      expect(s.surface).toBe(true)
      expect(s.focus, 'el foco va al campo de la hoja').toBe('cb-pac-search')
      await page.keyboard.type('mar', { delay: 15 })
      await page.waitForTimeout(350)
      const sheet = await page.evaluate(() => {
        const d = document.getElementById('cb-pac-surface'); const r = d.getBoundingClientRect()
        const f = document.getElementById('cb-pac-search').getBoundingClientRect()
        const rows = [...document.querySelectorAll('#cb-pac-list [role=option]')].map((o) => o.getBoundingClientRect().height)
        return { modal: d.matches(':modal'), sheet: d.classList.contains('g-combobox-surface--sheet'), top: r.top, w: r.width, vw: innerWidth, fieldTop: f.top - r.top, minRow: Math.min(...rows), n: rows.length, preview: Boolean(d.querySelector('.g-combobox__preview')), sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth, bodyTab: d.querySelector('.g-dialog__body').getAttribute('tabindex') }
      })
      expect(sheet).toMatchObject({ modal: true, sheet: true, preview: false, bodyTab: null })
      expect(sheet.top, 'anclada arriba').toBeLessThanOrEqual(1)
      expect(Math.abs(sheet.w - sheet.vw), 'ancho completo').toBeLessThanOrEqual(1)
      expect(sheet.fieldTop).toBeLessThan(120)
      expect(sheet.n).toBeGreaterThan(1)
      expect(sheet.minRow, 'opciones ≥ 44px').toBeGreaterThanOrEqual(44)
      expect(sheet.sw).toBeLessThanOrEqual(sheet.cw)
      await page.keyboard.press('Enter')
      await page.waitForFunction(() => !document.getElementById('cb-pac-surface').open)
      await frames(page, 3)
      s = await st(page, 'cb-pac')
      expect(await out(page, 'cb-out-pac')).toMatch(/^paciente: p\d{6}/)
      expect(s.focus, 'el foco vuelve al campo').toBe('cb-pac')
      expect(s.token).toBe(true)
      g = await geo(page, 'cb-pac')
      expect(g.sw, 'con valor, sin desbordamiento').toBeLessThanOrEqual(g.cw)
      const tok = await page.evaluate(() => { const t = document.querySelector('#cb-pac').closest('.g-combobox').querySelector('.g-combobox__token').getBoundingClientRect(); const c = document.getElementById('cb-pac').closest('.g-input__control').getBoundingClientRect(); return t.left >= c.left - 1 && t.right <= c.right + 1 })
      expect(tok, 'la ficha cabe en la caja').toBe(true)
      expect(errs, errs.join('\n')).toEqual([])
    })
  }

  test('RTL: la forma se alinea a la caja, dentro del visor; abre, navega y elige', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page)
    await page.locator('#cb-rtl').scrollIntoViewIfNeeded()
    await page.focus('#cb-rtl')
    await page.keyboard.press('ArrowDown')
    await frames(page, 3)
    const r = await page.evaluate(() => {
      const c = document.getElementById('cb-rtl').closest('.g-input__control').getBoundingClientRect()
      const p = document.getElementById('cb-rtl-popup').getBoundingClientRect()
      const o = document.querySelector('#cb-rtl-list [role=option] .g-summary__title').getBoundingClientRect()
      return { dl: Math.abs(c.left - p.left), dr: Math.abs(c.right - p.right), inside: p.left >= 0 && p.right <= innerWidth, labelAtStart: c.right - o.right < c.width / 2, dir: getComputedStyle(document.getElementById('cb-rtl')).direction }
    })
    expect(r.dir).toBe('rtl')
    expect(r.dl).toBeLessThan(1)
    expect(r.dr).toBeLessThan(1)
    expect(r.inside).toBe(true)
    expect(r.labelAtStart, 'el texto empieza en el borde de inicio (derecho)').toBe(true)
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await frames(page)
    const s = await st(page, 'cb-rtl')
    expect(s.value).toBe('طبيب أطفال')
    expect(s.token).toBe(true)
    expect(errs, errs.join('\n')).toEqual([])
  })

  test('contraste ≥ 4.5: opción activa, encabezado de grupo, código y línea secundaria', async ({ page }) => {
    await open(page)
    await type(page, 'cb-dx', 'diab')
    // La opción es una GSummary (#356): título, código y línea secundaria son sus partes
    const cA = await contrast(page, '#cb-dx-list .is-active .g-summary__title')
    const cG = await contrast(page, '#cb-dx-list .g-combobox__group-label')
    const cC = await contrast(page, '#cb-dx-list .is-active .g-summary__code')
    const cD = await contrast(page, '#cb-dx-list .is-active .g-summary__subtitle')
    for (const [name, c] of [['activa', cA], ['grupo', cG], ['código', cC], ['secundaria', cD]]) expect(c, `${name} ${c?.toFixed(2)}`).toBeGreaterThanOrEqual(4.5)
    // Y en la lista de pacientes, el rótulo y el valor de un dato de la ficha activa
    await type(page, 'cb-pac', 'maría garcía', { wait: 350 })
    const cL = await contrast(page, '#cb-pac-list .is-active .g-summary__fact-label')
    const cV = await contrast(page, '#cb-pac-list .is-active .g-summary__fact-value')
    for (const [name, c] of [['rótulo', cL], ['valor', cV]]) expect(c, `${name} ${c?.toFixed(2)}`).toBeGreaterThanOrEqual(4.5)
  })
})

// En WebKit con toque, el preventDefault de pointerdown cancela el click (hallazgo 4 de design/lab/time-field/auditoria.md):
// la flecha, las opciones y limpiar actúan en touchend
test.describe('GCombobox · toque (hasTouch + isMobile)', () => {
  test.skip(({ browserName }) => browserName === 'firefox', 'Firefox: sin isMobile ni puntero grueso en Playwright')
  test.use({ hasTouch: true, isMobile: true })
  test('un toque en la flecha abre, en una opción la elige y en limpiar borra', async ({ page }) => {
    const errs = await watchConsole(page)
    await open(page, { width: 390, height: 844 })
    const box = page.locator('#cb-dx >> xpath=ancestor::div[contains(@class,"g-combobox")][1]')
    await box.scrollIntoViewIfNeeded()
    await box.locator('.g-combobox__arrow').tap()
    await frames(page, 4)
    expect(await page.locator('#cb-dx').getAttribute('aria-expanded')).toBe('true')
    const lb = await page.locator('#cb-dx').getAttribute('aria-controls')
    await page.locator(`#${lb} [role=option]`).first().tap()
    await frames(page, 4)
    expect(await out(page, 'cb-out-dx')).not.toBe('dx: null')
    await expect(page.locator('#cb-dx')).toHaveAttribute('aria-expanded', 'false')
    await box.locator('.g-combobox__clear').tap()
    await frames(page, 4)
    expect(await out(page, 'cb-out-dx')).toBe('dx: null')
    expect(errs).toEqual([])
  })
})
