// GENERADO por scripts/sync-defaults.mjs desde packages/vue/src/styles/defaults.css. No editar a mano.
// Una prueba comprueba que no se desfase.
export const DEFAULTS = {
  "--g-color-brand": "#1F1F1F",
  "--g-color-brand-strong": "#333333",
  "--g-color-brand-soft": "#F0F0F0",
  "--g-color-brand-text": "#1F1F1F",
  "--g-color-on-brand": "#FFFFFF",
  "--g-color-on-brand-soft": "#1F1F1F",
  "--g-color-accent": "#0B63CE",
  "--g-color-accent-strong": "#024DA7",
  "--g-color-accent-soft": "#E9F1FD",
  "--g-color-accent-text": "#0B63CE",
  "--g-color-on-accent": "#FFFFFF",
  "--g-color-on-accent-soft": "#0B63CE",
  "--g-color-neutral": "#6B6B6B",
  "--g-color-neutral-strong": "#555555",
  "--g-color-neutral-soft": "#F0F0F0",
  "--g-color-neutral-text": "#6B6B6B",
  "--g-color-on-neutral": "#FFFFFF",
  "--g-color-on-neutral-soft": "#555555",
  "--g-color-success": "#1E7A46",
  "--g-color-success-strong": "#026133",
  "--g-color-success-soft": "#DFF8E5",
  "--g-color-success-text": "#1E7A46",
  "--g-color-on-success": "#FFFFFF",
  "--g-color-on-success-soft": "#1E7A46",
  "--g-color-warning": "#8F5B00",
  "--g-color-warning-strong": "#704806",
  "--g-color-warning-soft": "#FFEDD9",
  "--g-color-warning-text": "#8F5B00",
  "--g-color-on-warning": "#FFFFFF",
  "--g-color-on-warning-soft": "#8F5B00",
  "--g-color-danger": "#C4321F",
  "--g-color-danger-strong": "#A51603",
  "--g-color-danger-soft": "#FDECE8",
  "--g-color-danger-text": "#C4321F",
  "--g-color-on-danger": "#FFFFFF",
  "--g-color-on-danger-soft": "#C4321F",
  "--g-color-info": "#0B63CE",
  "--g-color-info-strong": "#024DA7",
  "--g-color-info-soft": "#E9F1FD",
  "--g-color-info-text": "#0B63CE",
  "--g-color-on-info": "#FFFFFF",
  "--g-color-on-info-soft": "#0B63CE",
  "--g-color-bg": "#FFFFFF",
  "--g-color-surface": "#FFFFFF",
  "--g-color-surface-sunken": "#F6F6F6",
  "--g-color-text": "#1A1A1A",
  "--g-color-text-muted": "#555555",
  "--g-color-text-subtle": "#6E6E6E",
  "--g-color-border": "rgb(0 0 0 / 0.08)",
  "--g-color-border-strong": "rgb(0 0 0 / 0.16)",
  "--g-color-border-control": "#8A8A8A",
  "--g-color-focus": "var(--g-color-accent-text)",
  "--g-color-primary": "var(--g-color-brand)",
  "--g-color-primary-strong": "var(--g-color-brand-strong)",
  "--g-color-primary-soft": "var(--g-color-brand-soft)",
  "--g-color-primary-text": "var(--g-color-brand-text)",
  "--g-color-on-primary": "var(--g-color-on-brand)",
  "--g-color-on-primary-soft": "var(--g-color-on-brand-soft)",
  "--g-color-link": "var(--g-color-accent-text)",
  "--g-color-selection": "var(--g-color-accent-soft)",
  "--g-color-active": "var(--g-color-accent)",
  "--g-calendar-grid-color": "var(--g-color-border)",
  "--g-calendar-unavailable-color": "var(--g-color-border-strong)",
  "--g-calendar-now-color": "var(--g-color-danger)",
  "--g-glass-tint": "#FFFFFF",
  "--g-glass-opacity": "0.62",
  "--g-glass-filter": "blur(14px) saturate(1.8)",
  "--g-glass-edge": "rgb(255 255 255 / 0.75)",
  "--g-glass-sheen": "rgb(255 255 255 / 0.55)",
  "--g-surface-shell": "var(--g-color-surface-sunken)",
  "--g-surface-inset": "var(--g-color-surface)",
  "--g-surface-backdrop": "rgb(0 0 0 / 0.32)",
  "--g-tabs-track": "rgb(0 0 0 / 0.05)",
  "--g-tabs-thumb": "var(--g-color-surface)",
  "--g-tabs-band": "rgb(0 0 0 / 0.04)",
  "--g-tabs-panel": "var(--g-color-surface)",
  "--g-card-hover": "rgb(0 0 0 / 0.03)",
  "--g-card-pressed": "rgb(0 0 0 / 0.07)",
  "--g-card-selected": "rgb(0 0 0 / 0.045)",
  "--g-card-scrim": "rgb(0 0 0 / 0.62)",
  "--g-card-on-scrim": "#FFFFFF",
  "--g-shadow-1": "0 1px 2px rgb(0 0 0 / 0.05)",
  "--g-shadow-2": "0 4px 12px -4px rgb(0 0 0 / 0.10)",
  "--g-shadow-3": "0 16px 40px -12px rgb(0 0 0 / 0.18)",
  "--g-radius-none": "0",
  "--g-radius-xs": "3px",
  "--g-radius-sm": "4px",
  "--g-radius-md": "6px",
  "--g-radius-lg": "8px",
  "--g-radius-xl": "12px",
  "--g-radius-pill": "999px",
  "--g-radius-shape": "var(--g-radius-md)",
  "--g-border-width": "1px",
  "--g-focus-width": "2px",
  "--g-focus-offset": "2px",
  "--g-duration-fast": "120ms",
  "--g-duration-press": "160ms",
  "--g-duration-spin": "800ms",
  "--g-duration-slow": "calc(var(--g-duration-press) * 1.5)",
  "--g-ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
  "--g-ease-out": "cubic-bezier(0.23, 1, 0.32, 1)",
  "--g-ease-spring": "linear(0, 0.081, 0.258, 0.46, 0.644, 0.793, 0.901, 0.972, 1.013, 1.033, 1.038, 1.036, 1.029, 1.021, 1.014, 1.008, 1.004, 1.001, 1, 0.999, 1)",
  "--g-ease-bounce": "linear(0, 0.124, 0.401, 0.708, 0.963, 1.127, 1.199, 1.197, 1.151, 1.088, 1.029, 0.987, 0.964, 0.958, 0.964, 0.976, 0.989, 0.999, 1.006, 1.008, 1.008, 1.006, 1)",
  "--g-press-scale": "0.97",
  "--g-tabs-mark-default": "calc(var(--g-border-width) * 3)",
  "--g-tabs-mark-comfortable": "calc(var(--g-border-width) * 2)",
  "--g-tabs-mark-compact": "calc(var(--g-border-width) * 2)",
  "--g-surface-gap": "calc(var(--g-space-1) * 1.5)",
  "--g-surface-radius": "var(--g-radius-xl)",
  "--g-surface-radius-inset": "max(0px, calc(var(--g-surface-radius) - var(--g-surface-gap)))",
  "--g-sidebar-width": "calc(var(--g-space-1) * 66)",
  "--g-sidebar-rail": "calc(var(--g-space-1) * 16)",
  "--g-sidebar-bar": "calc(var(--g-space-1) * 17)",
  "--g-widget-row": "calc(var(--g-space-1) * 28)",
  "--g-widget-gap": "calc(var(--g-space-1) * 4)",
  "--g-form-gap": "calc(var(--g-space-1) * 5)",
  "--g-form-column-gap": "var(--g-space-4)",
  "--g-form-section-gap": "calc(var(--g-space-1) * 10)",
  "--g-divider-inset": "calc(var(--g-space-1) * 2)",
  "--g-space-1": "4px",
  "--g-space-2": "8px",
  "--g-space-3": "12px",
  "--g-space-4": "16px",
  "--g-space-5": "20px",
  "--g-space-6": "24px",
  "--g-space-8": "32px",
  "--g-space-12": "48px",
  "--g-space-16": "64px",
  "--g-font-ui": "\"Instrument Sans Variable\", \"Instrument Sans\", system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
  "--g-font-title": "var(--g-font-ui)",
  "--g-font-display": "var(--g-font-ui)",
  "--g-text-caption-size": "0.75rem",
  "--g-text-caption-line": "1rem",
  "--g-text-caption-tracking": "0",
  "--g-text-caption-weight": "500",
  "--g-text-body-sm-size": "0.875rem",
  "--g-text-body-sm-line": "1.25rem",
  "--g-text-body-sm-tracking": "0",
  "--g-text-body-sm-weight": "400",
  "--g-text-body-size": "1rem",
  "--g-text-body-line": "1.5rem",
  "--g-text-body-tracking": "0",
  "--g-text-body-weight": "400",
  "--g-text-title-sm-size": "1.25rem",
  "--g-text-title-sm-line": "1.75rem",
  "--g-text-title-sm-tracking": "-0.004em",
  "--g-text-title-sm-weight": "600",
  "--g-text-title-size": "1.5625rem",
  "--g-text-title-line": "2.25rem",
  "--g-text-title-tracking": "-0.008em",
  "--g-text-title-weight": "600",
  "--g-text-title-lg-size": "1.9531rem",
  "--g-text-title-lg-line": "2.5rem",
  "--g-text-title-lg-tracking": "-0.014em",
  "--g-text-title-lg-weight": "600",
  "--g-text-display-size": "2.4414rem",
  "--g-text-display-line": "3rem",
  "--g-text-display-tracking": "-0.022em",
  "--g-text-display-weight": "600",
  "--g-text-action-weight": "500"
}

// Grupo de color del tema oscuro (bloque [data-theme="dark"], tokens.md §15)
export const DARK = {
  "--g-color-brand": "#F2F2F2",
  "--g-color-brand-strong": "#FFFFFF",
  "--g-color-brand-soft": "#2A2A2A",
  "--g-color-brand-text": "#F2F2F2",
  "--g-color-on-brand": "#17151A",
  "--g-color-on-brand-soft": "#F2F2F2",
  "--g-color-accent": "#3383F0",
  "--g-color-accent-strong": "#4D96FF",
  "--g-color-accent-soft": "#0E2442",
  "--g-color-accent-text": "#3383F0",
  "--g-color-on-accent": "#17151A",
  "--g-color-on-accent-soft": "#3A89F7",
  "--g-color-neutral": "#858585",
  "--g-color-neutral-strong": "#979797",
  "--g-color-neutral-soft": "#242424",
  "--g-color-neutral-text": "#858585",
  "--g-color-on-neutral": "#17151A",
  "--g-color-on-neutral-soft": "#8B8B8B",
  "--g-color-success": "#3F9560",
  "--g-color-success-strong": "#52A871",
  "--g-color-success-soft": "#132A1B",
  "--g-color-success-text": "#3F9560",
  "--g-color-on-success": "#17151A",
  "--g-color-on-success-soft": "#459C65",
  "--g-color-warning": "#AF792F",
  "--g-color-warning-strong": "#C28B43",
  "--g-color-warning-soft": "#30210D",
  "--g-color-warning-text": "#AF792F",
  "--g-color-on-warning": "#17151A",
  "--g-color-on-warning-soft": "#B88239",
  "--g-color-danger": "#E4523D",
  "--g-color-danger-strong": "#FA664F",
  "--g-color-danger-soft": "#3E160F",
  "--g-color-danger-text": "#E4523D",
  "--g-color-on-danger": "#17151A",
  "--g-color-on-danger-soft": "#EB5843",
  "--g-color-info": "#3383F0",
  "--g-color-info-strong": "#4D96FF",
  "--g-color-info-soft": "#0E2442",
  "--g-color-info-text": "#3383F0",
  "--g-color-on-info": "#17151A",
  "--g-color-on-info-soft": "#3A89F7",
  "--g-color-bg": "#141414",
  "--g-color-surface": "#1C1C1C",
  "--g-color-surface-sunken": "#101010",
  "--g-color-text": "#F2F2F2",
  "--g-color-text-muted": "#B8B8B8",
  "--g-color-text-subtle": "#9C9C9C",
  "--g-color-border": "rgb(255 255 255 / 0.10)",
  "--g-color-border-strong": "rgb(255 255 255 / 0.20)",
  "--g-color-border-control": "#808080",
  "--g-color-focus": "var(--g-color-accent-text)",
  "--g-color-primary": "var(--g-color-brand)",
  "--g-color-primary-strong": "var(--g-color-brand-strong)",
  "--g-color-primary-soft": "var(--g-color-brand-soft)",
  "--g-color-primary-text": "var(--g-color-brand-text)",
  "--g-color-on-primary": "var(--g-color-on-brand)",
  "--g-color-on-primary-soft": "var(--g-color-on-brand-soft)",
  "--g-color-link": "var(--g-color-accent-text)",
  "--g-color-selection": "var(--g-color-accent-soft)",
  "--g-color-active": "var(--g-color-accent)",
  "--g-calendar-grid-color": "var(--g-color-border)",
  "--g-calendar-unavailable-color": "var(--g-color-border-strong)",
  "--g-calendar-now-color": "var(--g-color-danger)",
  "--g-glass-tint": "#1C1C1C",
  "--g-glass-opacity": "0.72",
  "--g-glass-filter": "blur(14px) saturate(1.8)",
  "--g-glass-edge": "rgb(255 255 255 / 0.18)",
  "--g-glass-sheen": "rgb(255 255 255 / 0.10)",
  "--g-surface-shell": "var(--g-color-surface-sunken)",
  "--g-surface-inset": "var(--g-color-surface)",
  "--g-surface-backdrop": "rgb(0 0 0 / 0.6)",
  "--g-tabs-track": "rgb(255 255 255 / 0.08)",
  "--g-tabs-thumb": "rgb(255 255 255 / 0.12)",
  "--g-tabs-band": "rgb(255 255 255 / 0.05)",
  "--g-tabs-panel": "var(--g-color-surface)",
  "--g-card-hover": "rgb(255 255 255 / 0.04)",
  "--g-card-pressed": "rgb(255 255 255 / 0.09)",
  "--g-card-selected": "rgb(255 255 255 / 0.06)",
  "--g-card-scrim": "rgb(0 0 0 / 0.68)",
  "--g-card-on-scrim": "#FFFFFF",
  "--g-shadow-1": "0 1px 2px rgb(0 0 0 / 0.30)",
  "--g-shadow-2": "0 4px 12px -4px rgb(0 0 0 / 0.50)",
  "--g-shadow-3": "0 16px 40px -12px rgb(0 0 0 / 0.60)"
}
